include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true
    cascade_invocations: false

analyzer:
  exclude:
    - lib/src/app/locator.config.dart
    - lib/src/generated/codegen_loader.g.dart
    - lib/src/generated/locale_keys.g.dart
