include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    argument_type_not_assignable: false
    prefer_final_fields: false
    public_member_api_docs: true

analyzer:
  exclude:
    - lib/app/locator.config.dart
    - lib/generated/**
  errors:
    argument_type_not_assignable: false
