name: elaichi
description: Campus Guide for NIT Rourkela

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'
dependency_overrides:
  get_it: ^7.0.0

dependencies:
  flutter:
    sdk: flutter

  # Image caching
  cached_network_image: ^3.0.0

  # Logging
  logger: ^1.0.0

  # State management
  stacked: ^2.1.6

  # Navigation
  stacked_services: ^0.8.6

  # Inversion of control(dependency injection)
  get_it: ^7.0.0
  dartz: ^0.10.0-nullsafety.2

  # Themeing
  stacked_themes: ^0.3.2
  google_fonts: ^2.1.0

  # Localisation
  easy_localization: ^3.0.0

  # Local database
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # GraphQL client library
  graphql: ^5.0.0-nullsafety.5

  # Authentications
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4

  # Overlay UI
  flutter_portal: ^0.4.0
  # Load SVG (Logos)
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.9
  very_good_analysis: ^2.1.1

  build_runner: ^2.0.4
  auto_route_generator: ^2.1.0
  injectable_generator: ^1.4.1

  # Local database
  hive_generator: ^1.1.0
  stacked_generator: ^0.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Avenue
      fonts:
        - asset: assets/icons/avenue_icons.ttf
