name: elaichi
description: Campus guide of NIT Rourkela

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  stacked: ^1.6.0

  #navigation
  auto_route: ^0.6.6
  stacked_services: ^0.5.0

  #inversion of control(dependency injection)
  get_it: ^4.0.2
  injectable: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

  build_runner:
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.2

flutter:
  uses-material-design: true
