test:
  files:
    - "(.\/)?elaichi/test.*"

ui:
  files:
    - "(.\/)?elaichi/lib/ui.*"

services:
  files:
    - "(.\/)?elaichi/lib/services.*"

android_folder:
  files:
    - "(.\/)?elaichi/android.*"

ios_folder:
  files:
    - "(.\/)?elaichi/ios.*"

repo_root:
  files:
    - "[^\/]*"

actions:
  files:
    - "(.\/)?.github.*"

mergable:
  mergable: true

small:
  size-below: 10
medium:
  size-above: 9
  size-below: 100
large:
  size-above: 100